gem 'pry'
gem 'bcrypt'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'shotgun'
gem 'sqlite3'
gem 'thin'
gem 'rake'
gem 'require_all'
